import type { DestinationRecommendation } from "@/app/find-destination/_lib/types";

/**
 * Curated destination catalog used by the mock recommender and details pages.
 * Keep UI free of recommendation logic — score/select via the AI service layer.
 */
export const DESTINATION_CATALOG: DestinationRecommendation[] = [
  {
    slug: "goa-india",
    name: "Goa",
    country: "India",
    region: "india",
    shortDescription: "Sun-soaked beaches, easy nights, and seafood by the shore.",
    overview:
      "Goa blends Portuguese heritage with palm-lined beaches and a relaxed coastal rhythm — ideal for short escapes and longer unwind trips.",
    whyItMatches: "Beach weather, nightlife, and flexible budgets line up for easy coastal holidays.",
    bestMonths: ["Nov", "Dec", "Jan", "Feb", "Mar"],
    estimatedBudgetInr: { min: 25000, max: 90000 },
    idealDuration: "3–7 days",
    topAttractions: ["Palolem Beach", "Old Goa churches", "Anjuna flea market", "Dudhsagar Falls"],
    travelStyle: "Relaxing to moderate",
    confidenceScore: 92,
    imageSearchKeyword: "goa beach india",
    imageUrl:
      "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80",
    weatherSummary: "Warm, humid winters; monsoon from June–September.",
    foodHighlights: ["Fish curry rice", "Bebinca", "Beach shacks"],
    transportNotes: "Fly into GOI/GOX; scooters and cabs cover short hops.",
    packingTips: ["Light cottons", "Reef-safe sunscreen", "Evening layer"],
    travelTips: ["Book beach stays early in Dec–Jan", "Use prepaid taxis from airports"],
    safetyNotes: "Tourist-friendly; use normal night-out precautions.",
    travelPlaceSlug: "goa-india",
  },
  {
    slug: "manali-india",
    name: "Manali",
    country: "India",
    region: "india",
    shortDescription: "Alpine valleys, pine forests, and mountain adventure.",
    overview:
      "Manali is a Himalayan base for snow, road trips, and active days with café culture in Old Manali.",
    whyItMatches: "Mountains, adventure, and colder weather preferences map cleanly here.",
    bestMonths: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun"],
    estimatedBudgetInr: { min: 20000, max: 70000 },
    idealDuration: "4–7 days",
    topAttractions: ["Solang Valley", "Rohtang / Atal Tunnel side trips", "Hadimba Temple", "Old Manali"],
    travelStyle: "Active",
    confidenceScore: 90,
    imageSearchKeyword: "manali himalaya snow",
    imageUrl:
      "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80",
    weatherSummary: "Cold winters with snow; pleasant summers in the valley.",
    foodHighlights: ["Siddu", "Trout", "Tibetan cafés"],
    transportNotes: "Overnight bus/volvo from Delhi; flights via Bhuntar (KUU).",
    packingTips: ["Warm layers", "Waterproof shoes", "Sunglasses for snow glare"],
    travelTips: ["Check road status in winter", "Acclimatize before high passes"],
    safetyNotes: "Mountain roads need careful driving; hire experienced drivers.",
    travelPlaceSlug: "manali-india",
  },
  {
    slug: "jaipur-india",
    name: "Jaipur",
    country: "India",
    region: "india",
    shortDescription: "Pink City forts, bazaars, and royal heritage walks.",
    overview:
      "Jaipur packs forts, palaces, and craft markets into a highly walkable cultural capital.",
    whyItMatches: "History, photography, and shopping shine for culture-forward travelers.",
    bestMonths: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    estimatedBudgetInr: { min: 18000, max: 65000 },
    idealDuration: "3–5 days",
    topAttractions: ["Amber Fort", "City Palace", "Hawa Mahal", "Johari Bazaar"],
    travelStyle: "Moderate",
    confidenceScore: 88,
    imageSearchKeyword: "jaipur amber fort",
    imageUrl:
      "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1200&q=80",
    weatherSummary: "Pleasant winters; hot summers — plan early starts.",
    foodHighlights: ["Dal baati churma", "Ghewar", "Lassi"],
    transportNotes: "Well connected by flight, train, and road from Delhi.",
    packingTips: ["Comfortable walking shoes", "Sun hat", "Modest evening wear for palaces"],
    travelTips: ["Buy tickets online for Amber Fort", "Hire an authorized guide once"],
    safetyNotes: "Busy bazaars — keep valuables secure.",
    travelPlaceSlug: "jaipur-india",
  },
  {
    slug: "rishikesh-india",
    name: "Rishikesh",
    country: "India",
    region: "india",
    shortDescription: "Ganga-side yoga, rafting, and spiritual downtime.",
    overview:
      "Rishikesh balances adventure sports with ashrams, cafés, and riverside sunsets.",
    whyItMatches: "Spiritual and adventure interests overlap for active, mindful trips.",
    bestMonths: ["Sep", "Oct", "Nov", "Feb", "Mar", "Apr", "May"],
    estimatedBudgetInr: { min: 15000, max: 50000 },
    idealDuration: "3–6 days",
    topAttractions: ["Laxman Jhula", "Beatles Ashram", "River rafting", "Evening aarti"],
    travelStyle: "Active to relaxing",
    confidenceScore: 87,
    imageSearchKeyword: "rishikesh ganga bridge",
    imageUrl:
      "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1200&q=80",
    weatherSummary: "Pleasant most of the year; monsoon rains can be heavy.",
    foodHighlights: ["Cafe culture", "Satvik thalis", "Himalayan bakeries"],
    transportNotes: "Train to Haridwar + cab, or direct buses from Delhi.",
    packingTips: ["Quick-dry clothes", "Water shoes for rafting", "Light jacket"],
    travelTips: ["Book rafting with certified operators", "Carry cash for smaller cafés"],
    safetyNotes: "Respect river currents; follow local guidance.",
    travelPlaceSlug: "rishikesh-india",
  },
  {
    slug: "udaipur-india",
    name: "Udaipur",
    country: "India",
    region: "india",
    shortDescription: "Lake palaces, rooftop sunsets, and romantic old-city lanes.",
    overview:
      "Udaipur is one of India’s most photogenic cities — lakes, courtyards, and slow evenings.",
    whyItMatches: "Ideal for couples seeking pleasant weather, history, and photography.",
    bestMonths: ["Oct", "Nov", "Dec", "Jan", "Feb", "Mar"],
    estimatedBudgetInr: { min: 22000, max: 85000 },
    idealDuration: "3–5 days",
    topAttractions: ["City Palace", "Lake Pichola", "Sajjangarh", "Old city cafés"],
    travelStyle: "Relaxing",
    confidenceScore: 91,
    imageSearchKeyword: "udaipur lake palace",
    imageUrl:
      "https://images.unsplash.com/photo-1599661046289-e62895b5f9a0?auto=format&fit=crop&w=1200&q=80",
    weatherSummary: "Cool winters; warm days from March onward.",
    foodHighlights: ["Dal bati", "Laal maas", "Rooftop thalis"],
    transportNotes: "Flights to UDR; scenic road from Jaipur/Jodhpur.",
    packingTips: ["Smart-casual for sunset dinners", "Comfortable shoes"],
    travelTips: ["Book a lake-view dinner early", "Boat rides at golden hour"],
    safetyNotes: "Generally very safe for couples and families.",
    travelPlaceSlug: "udaipur-india",
  },
  {
    slug: "andaman-india",
    name: "Andaman Islands",
    country: "India",
    region: "india",
    shortDescription: "Turquoise water, snorkeling, and unhurried island days.",
    overview:
      "The Andamans deliver beach weather, marine life, and a far-from-mainland calm.",
    whyItMatches: "Beach, wildlife snorkeling, and relaxation preferences score highly.",
    bestMonths: ["Nov", "Dec", "Jan", "Feb", "Mar", "Apr"],
    estimatedBudgetInr: { min: 45000, max: 150000 },
    idealDuration: "5–8 days",
    topAttractions: ["Havelock / Swaraj Dweep", "Radhanagar Beach", "Scuba / snorkel", "Cellular Jail"],
    travelStyle: "Relaxing",
    confidenceScore: 89,
    imageSearchKeyword: "andaman havelock beach",
    imageUrl:
      "https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=1200&q=80",
    weatherSummary: "Tropical; best outside peak monsoon.",
    foodHighlights: ["Fresh seafood", "Coconut curries"],
    transportNotes: "Fly to Port Blair; ferries/flights to islands.",
    packingTips: ["Reef-safe sunscreen", "Dry bag", "Mosquito repellent"],
    travelTips: ["Pre-book ferries in peak season", "Respect marine park rules"],
    safetyNotes: "Swim in designated areas; watch ferry weather advisories.",
    travelPlaceSlug: "andaman-india",
  },
  {
    slug: "bali-indonesia",
    name: "Bali",
    country: "Indonesia",
    region: "international",
    shortDescription: "Temples, rice terraces, surf towns, and wellness retreats.",
    overview:
      "Bali mixes spiritual culture, beaches, and café creativity — a perennial favorite for first international trips.",
    whyItMatches: "Beaches, spirituality, food, and flexible travel styles all fit.",
    bestMonths: ["Apr", "May", "Jun", "Jul", "Aug", "Sep"],
    estimatedBudgetInr: { min: 70000, max: 220000 },
    idealDuration: "6–10 days",
    topAttractions: ["Ubud", "Uluwatu", "Tegallalang", "Nusa islands"],
    travelStyle: "Moderate",
    confidenceScore: 94,
    imageSearchKeyword: "bali rice terrace temple",
    imageUrl:
      "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80",
    weatherSummary: "Tropical; dry season is best for outdoor plans.",
    foodHighlights: ["Nasi goreng", "Satay", "Fresh juices"],
    transportNotes: "Fly into DPS; private drivers are common and affordable.",
    packingTips: ["Temple-appropriate cover-ups", "Mosquito repellent", "Light rain jacket"],
    travelTips: ["Mix Ubud + beach days", "Check visa-on-arrival rules"],
    safetyNotes: "Use helmets on scooters; drink bottled water.",
    travelPlaceSlug: "bali-indonesia",
  },
  {
    slug: "dubai-uae",
    name: "Dubai",
    country: "UAE",
    region: "international",
    shortDescription: "Skyline luxury, desert adventure, and world-class shopping.",
    overview:
      "Dubai is polished, easy to navigate, and packed with iconic experiences for short high-impact trips.",
    whyItMatches: "Luxury, shopping, and warm weather preferences align strongly.",
    bestMonths: ["Nov", "Dec", "Jan", "Feb", "Mar"],
    estimatedBudgetInr: { min: 90000, max: 300000 },
    idealDuration: "4–7 days",
    topAttractions: ["Burj Khalifa", "Desert safari", "Old Dubai souks", "Museum of the Future"],
    travelStyle: "Moderate to luxury",
    confidenceScore: 93,
    imageSearchKeyword: "dubai skyline night",
    imageUrl:
      "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80",
    weatherSummary: "Mild winters; extremely hot summers.",
    foodHighlights: ["Global dining", "Arabic sweets", "Brunch culture"],
    transportNotes: "Excellent metro + taxis; fly into DXB/DWC.",
    packingTips: ["Smart casual for malls/hotels", "Desert layers for evenings"],
    travelTips: ["Buy attraction tickets online", "Plan outdoor time for mornings"],
    safetyNotes: "Very safe; follow local customs on dress and public behavior.",
    travelPlaceSlug: "dubai-uae",
  },
  {
    slug: "singapore",
    name: "Singapore",
    country: "Singapore",
    region: "international",
    shortDescription: "Compact, ultra-clean, food-obsessed city adventures.",
    overview:
      "Singapore packs food, gardens, and family attractions into a seamless first-timer city break.",
    whyItMatches: "Food, shopping, and family-friendly city energy with easy logistics.",
    bestMonths: ["Feb", "Mar", "Apr", "Jul", "Aug", "Sep"],
    estimatedBudgetInr: { min: 80000, max: 250000 },
    idealDuration: "4–6 days",
    topAttractions: ["Gardens by the Bay", "Marina Bay Sands", "Hawker centres", "Sentosa"],
    travelStyle: "Moderate",
    confidenceScore: 90,
    imageSearchKeyword: "singapore marina bay gardens",
    imageUrl:
      "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1200&q=80",
    weatherSummary: "Warm and humid year-round with short showers.",
    foodHighlights: ["Hawker centres", "Chili crab", "Bak chor mee"],
    transportNotes: "MRT is excellent; Changi is a destination itself.",
    packingTips: ["Umbrella", "Comfortable walking shoes", "Light layers for AC"],
    travelTips: ["Use a stored-value transit card", "Book Gardens light show slots"],
    safetyNotes: "Extremely safe; strict local laws — follow signage.",
    travelPlaceSlug: "singapore",
  },
  {
    slug: "bangkok-thailand",
    name: "Bangkok",
    country: "Thailand",
    region: "international",
    shortDescription: "Temples, street food, markets, and late-night energy.",
    overview:
      "Bangkok is vibrant, affordable relative to many hubs, and endlessly rewarding for food and culture.",
    whyItMatches: "Food, nightlife, shopping, and warm weather are standout matches.",
    bestMonths: ["Nov", "Dec", "Jan", "Feb"],
    estimatedBudgetInr: { min: 55000, max: 160000 },
    idealDuration: "4–7 days",
    topAttractions: ["Grand Palace", "Chatuchak", "Chao Phraya boats", "Street food alleys"],
    travelStyle: "Active",
    confidenceScore: 88,
    imageSearchKeyword: "bangkok temple night market",
    imageUrl:
      "https://images.unsplash.com/photo-1563492065599-3520f775eeed?auto=format&fit=crop&w=1200&q=80",
    weatherSummary: "Hot; coolest and driest in winter months.",
    foodHighlights: ["Pad Thai", "Boat noodles", "Mango sticky rice"],
    transportNotes: "BTS/MRT + river boats; fly into BKK/DMK.",
    packingTips: ["Temple cover-ups", "Portable fan", "Crossbody bag"],
    travelTips: ["Carry a light scarf for temples", "Avoid peak heat midday walks"],
    safetyNotes: "Watch for scams around major attractions; use Grab.",
    travelPlaceSlug: "bangkok-thailand",
  },
  {
    slug: "paris-france",
    name: "Paris",
    country: "France",
    region: "international",
    shortDescription: "Museums, cafés, and timeless neighborhood wandering.",
    overview:
      "Paris rewards slow walks, museum days, and long meals — classic for couples and culture lovers.",
    whyItMatches: "History, photography, food, and moderate pacing fit beautifully.",
    bestMonths: ["Apr", "May", "Jun", "Sep", "Oct"],
    estimatedBudgetInr: { min: 120000, max: 300000 },
    idealDuration: "5–8 days",
    topAttractions: ["Louvre", "Eiffel Tower", "Montmartre", "Seine walks"],
    travelStyle: "Moderate",
    confidenceScore: 86,
    imageSearchKeyword: "paris eiffel tower evening",
    imageUrl:
      "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80",
    weatherSummary: "Mild springs/falls; chilly winters.",
    foodHighlights: ["Bakeries", "Bistros", "Cheese & wine"],
    transportNotes: "Metro is dense; fly into CDG/ORY.",
    packingTips: ["Layered outfits", "Comfortable shoes", "Light scarf"],
    travelTips: ["Prebook major museums", "Learn a few French phrases"],
    safetyNotes: "Watch for pickpockets in tourist zones.",
    travelPlaceSlug: "paris-france",
  },
  {
    slug: "tokyo-japan",
    name: "Tokyo",
    country: "Japan",
    region: "international",
    shortDescription: "Neon nights, quiet shrines, and obsessive food culture.",
    overview:
      "Tokyo is endlessly layered — futuristic districts beside temples, with world-class transit.",
    whyItMatches: "Food, photography, shopping, and active urban exploration.",
    bestMonths: ["Mar", "Apr", "May", "Oct", "Nov"],
    estimatedBudgetInr: { min: 130000, max: 300000 },
    idealDuration: "6–10 days",
    topAttractions: ["Shinjuku", "Asakusa", "Shibuya", "TeamLab / museums"],
    travelStyle: "Active",
    confidenceScore: 91,
    imageSearchKeyword: "tokyo street night shinjuku",
    imageUrl:
      "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1200&q=80",
    weatherSummary: "Pleasant springs/falls; humid summers; cold winters.",
    foodHighlights: ["Ramen", "Sushi counters", "Convenience-store gems"],
    transportNotes: "Suica/Pasmo + JR; fly into HND/NRT.",
    packingTips: ["Portable Wi‑Fi or eSIM", "Comfortable walking shoes", "Compact umbrella"],
    travelTips: ["Get an IC card day one", "Cash still helps in smaller spots"],
    safetyNotes: "Extremely safe; follow train etiquette.",
    travelPlaceSlug: "tokyo-japan",
  },
  {
    slug: "maldives",
    name: "Maldives",
    country: "Maldives",
    region: "international",
    shortDescription: "Overwater calm, reef colors, and pure beach weather.",
    overview:
      "The Maldives is the definition of warm-water luxury and disconnection — best for couples and honeymoons.",
    whyItMatches: "Beach weather, luxury, and relaxation preferences peak here.",
    bestMonths: ["Dec", "Jan", "Feb", "Mar", "Apr"],
    estimatedBudgetInr: { min: 180000, max: 300000 },
    idealDuration: "4–7 days",
    topAttractions: ["House reef snorkeling", "Sandbank picnic", "Sunset cruise", "Spa days"],
    travelStyle: "Relaxing / luxury",
    confidenceScore: 95,
    imageSearchKeyword: "maldives overwater bungalow",
    imageUrl:
      "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=1200&q=80",
    weatherSummary: "Tropical dry season is ideal; wetter mid-year.",
    foodHighlights: ["Resort dining", "Fresh seafood", "Tropical fruit"],
    transportNotes: "Fly into MLE; speedboat or seaplane transfers.",
    packingTips: ["Reef-safe sunscreen", "Light cover-ups", "Underwater phone case"],
    travelTips: ["Confirm transfer times with resort", "Budget for seaplane surcharges"],
    safetyNotes: "Resort islands are very safe; respect ocean conditions.",
    travelPlaceSlug: "maldives",
  },
  {
    slug: "kerala-india",
    name: "Kerala Backwaters",
    country: "India",
    region: "india",
    shortDescription: "Houseboats, coconut groves, and slow South-Indian days.",
    overview:
      "Kerala’s backwaters are made for unwinding — canals, cuisine, and soft green landscapes.",
    whyItMatches: "Relaxation, food, and pleasant tropical pacing.",
    bestMonths: ["Nov", "Dec", "Jan", "Feb", "Mar"],
    estimatedBudgetInr: { min: 25000, max: 90000 },
    idealDuration: "5–8 days",
    topAttractions: ["Alleppey houseboat", "Fort Kochi", "Tea trails (Munnar add-on)", "Ayurveda"],
    travelStyle: "Relaxing",
    confidenceScore: 89,
    imageSearchKeyword: "kerala backwaters houseboat",
    imageUrl:
      "https://images.unsplash.com/photo-1602216056333-66e636930ebb?auto=format&fit=crop&w=1200&q=80",
    weatherSummary: "Humid tropics; best outside heavy monsoon.",
    foodHighlights: ["Sadya", "Seafood", "Appam & stew"],
    transportNotes: "Fly into COK; drivers for multi-town loops.",
    packingTips: ["Mosquito repellent", "Light cottons", "Motion bands for boats if needed"],
    travelTips: ["Book reputable houseboats", "Combine Kochi + backwaters"],
    safetyNotes: "Choose licensed operators; life jackets on boats.",
    travelPlaceSlug: "kerala-india",
  },
  {
    slug: "leh-ladakh-india",
    name: "Leh-Ladakh",
    country: "India",
    region: "india",
    shortDescription: "High-altitude deserts, monasteries, and epic road trips.",
    overview:
      "Ladakh is raw and cinematic — best for adventure travelers who can handle altitude and long drives.",
    whyItMatches: "Mountains, adventure, photography, and road-trip energy.",
    bestMonths: ["Jun", "Jul", "Aug", "Sep"],
    estimatedBudgetInr: { min: 35000, max: 120000 },
    idealDuration: "7–12 days",
    topAttractions: ["Pangong Lake", "Nubra Valley", "Magnetic Hill", "Thiksey Monastery"],
    travelStyle: "Active",
    confidenceScore: 92,
    imageSearchKeyword: "ladakh pangong lake",
    imageUrl:
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80",
    weatherSummary: "Short summer season; freezing winters.",
    foodHighlights: ["Thukpa", "Momos", "Butter tea"],
    transportNotes: "Fly to IXL; road status depends on season.",
    packingTips: ["Altitude meds if advised", "Strong sunscreen", "Warm layers even in summer"],
    travelTips: ["Acclimatize 24–48h in Leh", "Avoid rushing high passes"],
    safetyNotes: "Altitude sickness is real — rest and hydrate.",
    travelPlaceSlug: "leh-ladakh-india",
  },
];

export function getDestinationBySlug(slug: string): DestinationRecommendation | null {
  const key = slug.trim().toLowerCase();
  return DESTINATION_CATALOG.find((d) => d.slug === key) ?? null;
}

export function getAllDestinationSlugs(): string[] {
  return DESTINATION_CATALOG.map((d) => d.slug);
}
