import type { LocalCityApps } from "@/app/app/local-apps/_lib/types";

function toIsoMonth(value: string): string {
  return `${value}-01T00:00:00.000Z`;
}

export const LOCAL_APPS_DATA: Record<string, LocalCityApps> = {
  bangkok: {
    city: "Bangkok",
    country: "Thailand",
    mustHave: ["Grab", "Google Maps", "Foodpanda"],
    lastUpdatedIso: toIsoMonth("2026-03"),
    categories: {
      Transport: [
        {
          id: "bangkok-grab",
          name: "Grab",
          category: "Transport",
          rating: 4.6,
          shortTips: ["Cheaper than taxis", "Use GrabBike during traffic", "Avoid airport taxis"],
          fullTips: [
            "Cheaper than taxis.",
            "Use GrabBike during traffic.",
            "Avoid airport taxis.",
          ],
          playStoreUrl: "https://grab.onelink.me",
          appStoreUrl: "https://grab.onelink.me",
          lastUpdatedIso: toIsoMonth("2026-03"),
          mostUseful: true,
        },
      ],
      Food: [
        {
          id: "bangkok-foodpanda",
          name: "Foodpanda",
          category: "Food",
          rating: 4.5,
          shortTips: ["Frequent discounts available", "Works well in central Bangkok"],
          fullTips: [
            "Frequent discounts available.",
            "Works well in central Bangkok.",
          ],
          playStoreUrl: "https://www.foodpanda.com",
          appStoreUrl: "https://www.foodpanda.com",
          lastUpdatedIso: toIsoMonth("2026-02"),
        },
      ],
      Payments: [
        {
          id: "bangkok-truemoney",
          name: "TrueMoney Wallet",
          category: "Payments",
          rating: 4.3,
          shortTips: ["Useful for local payments", "Not mandatory for tourists"],
          fullTips: [
            "Useful for local payments.",
            "Not mandatory for tourists.",
          ],
          playStoreUrl: "https://www.truemoney.com",
          appStoreUrl: "https://www.truemoney.com",
          lastUpdatedIso: toIsoMonth("2026-01"),
        },
      ],
      Navigation: [
        {
          id: "bangkok-google-maps",
          name: "Google Maps",
          category: "Navigation",
          rating: 4.8,
          shortTips: ["Best for walking routes", "Offline maps recommended"],
          fullTips: [
            "Best for walking routes.",
            "Offline maps recommended.",
          ],
          playStoreUrl: "https://maps.google.com",
          appStoreUrl: "https://maps.google.com",
          lastUpdatedIso: toIsoMonth("2026-03"),
        },
      ],
    },
  },
  dubai: {
    city: "Dubai",
    country: "UAE",
    mustHave: ["Careem", "Talabat", "RTA Dubai"],
    lastUpdatedIso: toIsoMonth("2026-03"),
    categories: {
      Transport: [
        {
          id: "dubai-careem",
          name: "Careem",
          category: "Transport",
          rating: 4.5,
          shortTips: ["Often cheaper than Uber", "Works for rides and deliveries"],
          fullTips: [
            "Often cheaper than Uber.",
            "Works for rides and deliveries.",
          ],
          playStoreUrl: "https://www.careem.com",
          appStoreUrl: "https://www.careem.com",
          lastUpdatedIso: toIsoMonth("2026-03"),
          mostUseful: true,
        },
        {
          id: "dubai-rta",
          name: "RTA Dubai",
          category: "Transport",
          rating: 4.3,
          shortTips: ["Manage Nol card", "Check metro timings"],
          fullTips: ["Manage Nol card.", "Check metro timings."],
          playStoreUrl: "https://www.rta.ae",
          appStoreUrl: "https://www.rta.ae",
          lastUpdatedIso: toIsoMonth("2026-02"),
        },
      ],
      Food: [
        {
          id: "dubai-talabat",
          name: "Talabat",
          category: "Food",
          rating: 4.4,
          shortTips: ["Wide restaurant coverage", "Frequent offers"],
          fullTips: ["Wide restaurant coverage.", "Frequent offers."],
          playStoreUrl: "https://www.talabat.com",
          appStoreUrl: "https://www.talabat.com",
          lastUpdatedIso: toIsoMonth("2026-02"),
        },
      ],
      Payments: [
        {
          id: "dubai-payments",
          name: "Google Pay / Cards",
          category: "Payments",
          rating: 4.3,
          shortTips: ["Cards are widely accepted", "Wallet app optional for tourists"],
          fullTips: [
            "Cards are widely accepted.",
            "Wallet app is optional for tourists.",
          ],
          playStoreUrl: "https://pay.google.com",
          appStoreUrl: "https://www.apple.com/wallet/",
          lastUpdatedIso: toIsoMonth("2026-02"),
        },
      ],
      Navigation: [
        {
          id: "dubai-google-maps",
          name: "Google Maps",
          category: "Navigation",
          rating: 4.8,
          shortTips: ["Accurate routes", "Use for metro navigation"],
          fullTips: ["Accurate routes.", "Use for metro navigation."],
          playStoreUrl: "https://maps.google.com",
          appStoreUrl: "https://maps.google.com",
          lastUpdatedIso: toIsoMonth("2026-03"),
        },
      ],
    },
  },
  singapore: {
    city: "Singapore",
    country: "Singapore",
    mustHave: ["Grab", "Citymapper", "Chope"],
    lastUpdatedIso: toIsoMonth("2026-03"),
    categories: {
      Transport: [
        {
          id: "sg-grab",
          name: "Grab",
          category: "Transport",
          rating: 4.6,
          shortTips: ["Reliable ride option", "Card payments preferred"],
          fullTips: ["Reliable ride option.", "Card payments preferred."],
          playStoreUrl: "https://grab.onelink.me",
          appStoreUrl: "https://grab.onelink.me",
          lastUpdatedIso: toIsoMonth("2026-03"),
          mostUseful: true,
        },
      ],
      Food: [
        {
          id: "sg-chope",
          name: "Chope",
          category: "Food",
          rating: 4.4,
          shortTips: ["Reserve restaurants easily", "Get dining deals"],
          fullTips: ["Reserve restaurants easily.", "Get dining deals."],
          playStoreUrl: "https://www.chope.co",
          appStoreUrl: "https://www.chope.co",
          lastUpdatedIso: toIsoMonth("2026-01"),
        },
      ],
      Payments: [],
      Navigation: [
        {
          id: "sg-citymapper",
          name: "Citymapper",
          category: "Navigation",
          rating: 4.7,
          shortTips: ["Best for public transport", "Shows exact MRT routes"],
          fullTips: ["Best for public transport.", "Shows exact MRT routes."],
          playStoreUrl: "https://citymapper.com",
          appStoreUrl: "https://citymapper.com",
          lastUpdatedIso: toIsoMonth("2026-02"),
        },
      ],
    },
  },
  bali: {
    city: "Bali",
    country: "Indonesia",
    mustHave: ["Gojek", "Grab", "Google Maps"],
    lastUpdatedIso: toIsoMonth("2026-03"),
    categories: {
      Transport: [
        {
          id: "bali-gojek",
          name: "Gojek",
          category: "Transport",
          rating: 4.7,
          shortTips: ["Cheapest option", "Bike taxis are fastest"],
          fullTips: ["Cheapest option.", "Bike taxis are fastest."],
          playStoreUrl: "https://www.gojek.com",
          appStoreUrl: "https://www.gojek.com",
          lastUpdatedIso: toIsoMonth("2026-03"),
          mostUseful: true,
        },
        {
          id: "bali-grab",
          name: "Grab",
          category: "Transport",
          rating: 4.6,
          shortTips: ["More reliable in tourist areas", "Slightly costlier than Gojek"],
          fullTips: ["More reliable in tourist areas.", "Slightly costlier than Gojek."],
          playStoreUrl: "https://grab.onelink.me",
          appStoreUrl: "https://grab.onelink.me",
          lastUpdatedIso: toIsoMonth("2026-03"),
        },
      ],
      Food: [],
      Payments: [],
      Navigation: [
        {
          id: "bali-google-maps",
          name: "Google Maps",
          category: "Navigation",
          rating: 4.8,
          shortTips: ["Essential for directions", "Download offline maps"],
          fullTips: ["Essential for directions.", "Download offline maps."],
          playStoreUrl: "https://maps.google.com",
          appStoreUrl: "https://maps.google.com",
          lastUpdatedIso: toIsoMonth("2026-03"),
        },
      ],
    },
  },
  london: {
    city: "London",
    country: "UK",
    mustHave: ["Citymapper", "Uber", "TfL Oyster"],
    lastUpdatedIso: toIsoMonth("2026-03"),
    categories: {
      Transport: [
        {
          id: "london-uber",
          name: "Uber",
          category: "Transport",
          rating: 4.5,
          shortTips: ["Works across the city", "Expensive during peak hours"],
          fullTips: ["Works across the city.", "Expensive during peak hours."],
          playStoreUrl: "https://www.uber.com",
          appStoreUrl: "https://www.uber.com",
          lastUpdatedIso: toIsoMonth("2026-03"),
          mostUseful: true,
        },
        {
          id: "london-tfl-oyster",
          name: "TfL Oyster",
          category: "Transport",
          rating: 4.4,
          shortTips: ["Manage Oyster card", "Track travel expenses"],
          fullTips: ["Manage Oyster card.", "Track travel expenses."],
          playStoreUrl: "https://tfl.gov.uk",
          appStoreUrl: "https://tfl.gov.uk",
          lastUpdatedIso: toIsoMonth("2026-01"),
        },
      ],
      Food: [],
      Payments: [],
      Navigation: [
        {
          id: "london-citymapper",
          name: "Citymapper",
          category: "Navigation",
          rating: 4.8,
          shortTips: ["Best for Tube navigation", "Shows delays and alternatives"],
          fullTips: ["Best for Tube navigation.", "Shows delays and alternatives."],
          playStoreUrl: "https://citymapper.com",
          appStoreUrl: "https://citymapper.com",
          lastUpdatedIso: toIsoMonth("2026-02"),
        },
      ],
    },
  },
  india: {
    city: "India",
    country: "India",
    mustHave: ["Uber", "Google Maps", "Zomato"],
    lastUpdatedIso: toIsoMonth("2026-03"),
    categories: {
      Transport: [
        {
          id: "india-uber",
          name: "Uber",
          category: "Transport",
          rating: 4.5,
          shortTips: ["Reliable in major cities", "Check pickup point carefully"],
          fullTips: ["Reliable in major cities.", "Check pickup point carefully."],
          playStoreUrl: "https://www.uber.com",
          appStoreUrl: "https://www.uber.com",
          lastUpdatedIso: toIsoMonth("2026-03"),
          mostUseful: true,
        },
      ],
      Food: [
        {
          id: "india-zomato",
          name: "Zomato",
          category: "Food",
          rating: 4.5,
          shortTips: ["Good local discovery", "Useful for reviews and menus"],
          fullTips: ["Good local discovery.", "Useful for reviews and menus."],
          playStoreUrl: "https://www.zomato.com",
          appStoreUrl: "https://www.zomato.com",
          lastUpdatedIso: toIsoMonth("2026-03"),
        },
      ],
      Payments: [
        {
          id: "india-gpay",
          name: "Google Pay",
          category: "Payments",
          rating: 4.4,
          shortTips: ["UPI is widely accepted", "Keep cash backup for remote areas"],
          fullTips: ["UPI is widely accepted.", "Keep cash backup for remote areas."],
          playStoreUrl: "https://pay.google.com",
          appStoreUrl: "https://www.apple.com/wallet/",
          lastUpdatedIso: toIsoMonth("2026-03"),
        },
      ],
      Navigation: [
        {
          id: "india-google-maps",
          name: "Google Maps",
          category: "Navigation",
          rating: 4.8,
          shortTips: ["Best turn-by-turn guidance", "Download offline maps"],
          fullTips: ["Best turn-by-turn guidance.", "Download offline maps."],
          playStoreUrl: "https://maps.google.com",
          appStoreUrl: "https://maps.google.com",
          lastUpdatedIso: toIsoMonth("2026-03"),
        },
      ],
    },
  },
  japan: {
    city: "Japan",
    country: "Japan",
    mustHave: ["Google Maps", "Japan Travel by NAVITIME", "Suica"],
    lastUpdatedIso: toIsoMonth("2026-03"),
    categories: {
      Transport: [
        {
          id: "japan-navitime",
          name: "Japan Travel by NAVITIME",
          category: "Transport",
          rating: 4.6,
          shortTips: ["Best for train routes", "Shows platform details and transfers"],
          fullTips: ["Best for train routes.", "Shows platform details and transfers."],
          playStoreUrl: "https://japantravel.navitime.com/en/",
          appStoreUrl: "https://japantravel.navitime.com/en/",
          lastUpdatedIso: toIsoMonth("2026-03"),
          mostUseful: true,
        },
        {
          id: "japan-suica",
          name: "Suica",
          category: "Transport",
          rating: 4.4,
          shortTips: ["Fast tap-and-go transit", "Useful for vending and convenience stores"],
          fullTips: ["Fast tap-and-go transit.", "Useful for vending and convenience stores."],
          playStoreUrl: "https://www.jreast.co.jp/multi/en/welcomesuica/",
          appStoreUrl: "https://www.jreast.co.jp/multi/en/welcomesuica/",
          lastUpdatedIso: toIsoMonth("2026-03"),
        },
      ],
      Food: [
        {
          id: "japan-tabelog",
          name: "Tabelog",
          category: "Food",
          rating: 4.5,
          shortTips: ["Great local restaurant discovery", "Useful ratings for nearby places"],
          fullTips: ["Great local restaurant discovery.", "Useful ratings for nearby places."],
          playStoreUrl: "https://tabelog.com/en/",
          appStoreUrl: "https://tabelog.com/en/",
          lastUpdatedIso: toIsoMonth("2026-03"),
        },
      ],
      Payments: [
        {
          id: "japan-paypay",
          name: "PayPay / Cards",
          category: "Payments",
          rating: 4.2,
          shortTips: ["Cards work in tourist zones", "Keep cash for smaller local shops"],
          fullTips: ["Cards work in tourist zones.", "Keep cash for smaller local shops."],
          playStoreUrl: "https://paypay.ne.jp",
          appStoreUrl: "https://paypay.ne.jp",
          lastUpdatedIso: toIsoMonth("2026-03"),
        },
      ],
      Navigation: [
        {
          id: "japan-google-maps",
          name: "Google Maps",
          category: "Navigation",
          rating: 4.8,
          shortTips: ["Reliable walking + train navigation", "Download offline areas before travel"],
          fullTips: ["Reliable walking + train navigation.", "Download offline areas before travel."],
          playStoreUrl: "https://maps.google.com",
          appStoreUrl: "https://maps.google.com",
          lastUpdatedIso: toIsoMonth("2026-03"),
        },
      ],
    },
  },
  global: {
    city: "Global",
    country: "International",
    mustHave: ["Google Maps", "Uber", "Booking.com"],
    lastUpdatedIso: toIsoMonth("2026-03"),
    categories: {
      Transport: [
        {
          id: "global-uber",
          name: "Uber",
          category: "Transport",
          rating: 4.5,
          shortTips: ["Works in many countries", "Check regional availability"],
          fullTips: ["Works in many countries.", "Check regional availability."],
          playStoreUrl: "https://www.uber.com",
          appStoreUrl: "https://www.uber.com",
          lastUpdatedIso: toIsoMonth("2026-03"),
          mostUseful: true,
        },
      ],
      Food: [
        {
          id: "global-food",
          name: "Tripadvisor",
          category: "Food",
          rating: 4.4,
          shortTips: ["Find nearby places", "Use ratings before choosing"],
          fullTips: ["Find nearby places.", "Use ratings before choosing."],
          playStoreUrl: "https://www.tripadvisor.com",
          appStoreUrl: "https://www.tripadvisor.com",
          lastUpdatedIso: toIsoMonth("2026-03"),
        },
      ],
      Payments: [
        {
          id: "global-payment",
          name: "Wise",
          category: "Payments",
          rating: 4.6,
          shortTips: ["Good for multi-currency", "Track FX rates"],
          fullTips: ["Good for multi-currency.", "Track FX rates."],
          playStoreUrl: "https://wise.com",
          appStoreUrl: "https://wise.com",
          lastUpdatedIso: toIsoMonth("2026-03"),
        },
      ],
      Navigation: [
        {
          id: "global-maps",
          name: "Google Maps",
          category: "Navigation",
          rating: 4.8,
          shortTips: ["Best default navigation", "Save offline regions"],
          fullTips: ["Best default navigation.", "Save offline regions."],
          playStoreUrl: "https://maps.google.com",
          appStoreUrl: "https://maps.google.com",
          lastUpdatedIso: toIsoMonth("2026-03"),
        },
      ],
    },
  },
};
